aeid: '5'
assay_info_keys:
- acid
- assay_component_endpoint_name
- assay_component_endpoint_desc
- assay_function_type
- normalized_data_type
- analysis_direction
- burst_assay
- key_positive_control
- signal_direction
- intended_target_type
- intended_target_type_sub
- intended_target_family
- intended_target_family_sub
bidirectional: 1

display_emoji: 1
do_fit: 1
do_hit: 1
drop_new_tables: 1
export_cols:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
export_path: export
fit_models:
- cnst
- poly1
- poly2
- pow
- exp2
- exp3
- exp4
- exp5
- hill
- gnls
fit_strategy: mle
n_jobs: -1
new_table_names:
- cutoffs
- output
output_cols:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
- concentration_unlogged
- response
- fitparams
parallelize: 1
profile: 1
test: 0
threshold_num_dp: 1000
track_fitted_params: 1
