# Binary classification
ignore_warnings: True


aeid: 784 # Assay id

activity_threshold: 0.9 # Activity threshold on continuous hitcall for binary classification

random_state: 0 # For reproducibility (observed high variance)

train_test_split_ratio: 0.15
train_val_split_ratio: 0.2

apply:
  smote: 0 # oversampling

grid_search_cv:
  n_splits: 5 # Number of folds
  n_repeats: 3 # Number of repeats
  scoring: f_beta # recall_macro, specificity, f1, roc_auc, accuracy
  # The F1 score is the harmonic mean of the precision and recall. The more generic F_beta score applies additional weights, valuing one of precision or recall more than the other.
  beta: 1 # F-beta = (1 + beta^2) * (precision * recall) / ((beta^2 * precision) + recall),  1 = F1, Two commonly used values for beta are 2, which weighs recall higher than precision, and 0.5, which weighs recall lower than precision.
  n_jobs: -1
  verbose: 1 # 0-3


threshold_moving: 1


# Don't forget to import all the classifiers
# and transformers you want to use
classifiers:
  # - name: SVC
  #   steps:
  #     - name: SVC

  # - name: KNeighborsClassifier
  #   steps:
  #     - name: PCA # hamming distance
  #     - name: KNeighborsClassifier
      
  # - name:  GaussianNB
  #   steps:
  #     - name: PCA
  #     - name: GaussianNB

  # - name: AdaBoostClassifier
  #   steps:
  #     # - name: PCA
  #     - name: AdaBoostClassifier

  # - name: MLPClassifier
  #   steps:
  #     - name: PCA
  #       args:
  #         n_components: [0.95]
  #     - name: MLPClassifier
  
  # - name: RandomForestClassifier
  #   steps:
  #     # - name: PCA
  #     - name: RandomForestClassifier
  #       args:
  #         n_estimators: [100, 150] # default = 100

  - name: XGBClassifier
    steps:
      # - name: VarianceThreshold
      - name: XGBClassifier
        args:
          n_estimators: [150] # default = 100
  





# non-negative matrix factorization





# Todo:
# compare with other assay, which chemicals are easy/difficult to predict
# put assay endpoint together with same mechanistic target
# also try edge case assay and try to tune 