aeid: '5'
apply_dropping_new_tables: 1
apply_fancy_logging: 1
apply_profiler: 1
apply_track_fitted_params: 1
fit_models:
- cnst
- poly1
- poly2
- pow
- hill
- gnls
n_jobs: 2
new_table_names:
- cutoffs
- output
threshold_num_datapoints: 1000
z_assay_info_keys:
- acid
- assay_component_endpoint_name
- assay_component_endpoint_desc
- assay_function_type
- normalized_data_type
- analysis_direction
- burst_assay
- key_positive_control
- signal_direction
- intended_target_type
- intended_target_type_sub
- intended_target_family
- intended_target_family_sub
z_export_cols:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
z_output_columns:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
- concentration_unlogged
- response
- fitparams
