enable_allowing_reading_remote: 0
enable_curve_fit_parameter_tracking: 0
enable_data_subsetting: 0
enable_dropping_all_new_tables: 1
enable_fancy_logging: 1
enable_profiling: 0
enable_reading_db: 0
enable_writing_db: 0
enable_output_compounds: 1

chunk_size: 10000
threshold_subsetting_aeids_on_count_compounds_tested: 2000 # -1 #2000
threshold_subsetting_aeids_on_hit_ratio: 0.005 # -1  #0.005
file_format: .parquet.gzip
instance_id: 0
instances_total: 4
max_num_datapoints_per_series_threshold: 1000
min_num_median_responses_threshold: 4
n_jobs: -1
bmr_scale: 1.349
bucket: datapytcpl

curve_fit_models:
  - cnst
  - poly1
  - poly2
  - pow
  - exp4
  - exp5
  - hill
  - sigmoid
  - gnls
new_db_tables:
  - cutoff
  - output
output_cols_filter:
  - ac50
  - acc
  - actop
  - bmd
  - ac1sd
  - aeid
  - best_aic_model
  - conc
  - fit_params
  - hitcall
  - resp
  - spid
  - top
  - dsstox_substance_id
report_assay_cols:
  - acid
  - analysis_direction
  - assay_component_endpoint_desc
  - assay_component_endpoint_name
  - assay_function_type
  - burst_assay
  - intended_target_family
  - intended_target_family_sub
  - intended_target_type
  - intended_target_type_sub
  - key_positive_control
  - normalized_data_type
  - signal_direction
