aeid: '5'
curve_fit_models:
- cnst
- poly1
- poly2
- pow
- exp4
- exp5
- hill
- gnls
data_file_format: parquet
enable_curve_fit_parameter_tracking: 1
enable_data_subsetting: 0
enable_dropping_new_tables: 1
enable_fancy_logging: 1
enable_profiling: 1
n_jobs: -1
new_db_tables:
- cutoffs
- output
num_datapoints_per_series_threshold: 1000
z_assay_info_keys:
- acid
- assay_component_endpoint_name
- assay_component_endpoint_desc
- assay_function_type
- normalized_data_type
- analysis_direction
- burst_assay
- key_positive_control
- signal_direction
- intended_target_type
- intended_target_type_sub
- intended_target_family
- intended_target_family_sub
z_export_cols:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
z_output_columns:
- aeid
- spid
- fit_model
- cutoff
- hitcall
- ac50
- bmd
- top
- conc
- response
- fit_params
