robin:
  db: prod_internal_invitrodb_v4_1
  host: localhost
  password: robin
  port: 3306
  username: robin
bossh:
  db: prod_internal_invitrodb_v4_1
  host: localhost
  password: root
  port: 3306
  username: root

