enable_allowing_reading_remote: 0
enable_curve_fit_parameter_tracking: 0
enable_data_subsetting: 0
enable_dropping_all_new_tables: 1
enable_fancy_logging: 1
enable_profiling: 0
enable_reading_db: 0
enable_writing_db: 1
enable_output_compounds: 1
enable_fetching_raw_data_from_db: 1

n_jobs: -1

minimize_method: L-BFGS-B
minimize_tol: 1e-6
minimize_maxiter: 500
minimize_maxfun: 500

activity_threshold: 0.9
chunk_size: 10000
threshold_subsetting_aeids_on_count_compounds_tested: 1000 # -1 #2000
threshold_subsetting_aeids_on_hit_ratio: 0.005 # -1  #0.005
threshold_cytotox_min_test: 0.8
threshold_cytotox_default_pt: 3
threshold_cytotox_hitc_num: 0.9

aeid_list_manual: 0
file_format: .parquet.gzip
instance_id: 0
instances_total: 4
max_num_datapoints_per_series_threshold: 1000
min_num_median_responses_threshold: 4
bmr_scale: 1.349
bucket: datapytcpl

curve_fit_models:
  - cnst
  - poly1
  - poly2
  - pow
  - exp2
#  - exp3
  - exp4
  - exp5
  - hill
  - sigmoid
  - gnls
new_db_tables:
  - cutoff
  - output
output_cols_filter:
  - ac50
  - ac95
  - acc
  - actop
  - bmd
  - ac1sd
  - aeid
  - best_aic_model
  - conc
  - fit_params
  - hitcall
  - resp
  - spid
  - top
  - dsstox_substance_id
  - cautionary_flags
  - fitc
report_assay_cols:
  - acid
  - analysis_direction
  - assay_component_endpoint_desc
  - assay_component_endpoint_name
  - assay_function_type
  - burst_assay
  - intended_target_family
  - intended_target_family_sub
  - intended_target_type
  - intended_target_type_sub
  - key_positive_control
  - normalized_data_type
  - signal_direction
